"""
esg_agent.pdf_writer — Markdown 报告转 PDF
═══════════════════════════════════════════════════════════════════════════════
依赖 reportlab，将 Phase 5 生成的 Markdown 报告转换为 PDF 归档。
"""

from __future__ import annotations
import logging
from pathlib import Path
from datetime import datetime
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, HRFlowable,
)
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

logger = logging.getLogger("esg_agent.pdf")


# 注册中文字体（macOS 系统字体）
def _register_fonts():
    """尝试注册中文字体，失败则回退到 Helvetica。"""
    font_paths = [
        # macOS
        ("/System/Library/Fonts/PingFang.ttc", "PingFang"),
        ("/System/Library/Fonts/STHeiti Light.ttc", "STHeiti"),
        ("/Library/Fonts/Arial Unicode.ttf", "ArialUni"),
        # Linux
        ("/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc", "WQY"),
        ("/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf", "Droid"),
    ]
    for path, name in font_paths:
        try:
            pdfmetrics.registerFont(TTFont(name, path))
            return name
        except Exception:
            continue
    return "Helvetica"


_FONT_NAME = _register_fonts()


def _md_to_pdf_elements(md_text: str) -> list:
    """将 Markdown 文本转换为 reportlab Platypus 元素列表。"""
    styles = getSampleStyleSheet()

    # 自定义样式
    title_style = ParagraphStyle("TitleCN", parent=styles["Title"], fontName=_FONT_NAME, fontSize=18, leading=24, spaceAfter=12)
    h2_style = ParagraphStyle("H2CN", parent=styles["Heading2"], fontName=_FONT_NAME, fontSize=14, leading=18, spaceBefore=16, spaceAfter=8)
    body_style = ParagraphStyle("BodyCN", parent=styles["Normal"], fontName=_FONT_NAME, fontSize=9, leading=14, spaceAfter=4)
    code_style = ParagraphStyle("CodeCN", parent=styles["Normal"], fontName=_FONT_NAME, fontSize=8, leading=11, leftIndent=12, textColor=HexColor("#555555"))
    footer_style = ParagraphStyle("FooterCN", parent=styles["Normal"], fontName=_FONT_NAME, fontSize=7, leading=10, textColor=HexColor("#999999"), alignment=TA_CENTER)

    elements = []
    lines = md_text.split("\n")

    for line in lines:
        stripped = line.strip()

        # 空行
        if not stripped:
            elements.append(Spacer(1, 6))
            continue

        # 标题
        if stripped.startswith("# ") and not stripped.startswith("## "):
            elements.append(Paragraph(_sanitize(stripped[2:]), title_style))
        elif stripped.startswith("## "):
            elements.append(Paragraph(_sanitize(stripped[3:]), h2_style))
        # 分隔线
        elif stripped == "---":
            elements.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#cccccc")))
            elements.append(Spacer(1, 6))
        # 引用
        elif stripped.startswith("> "):
            elements.append(Paragraph(_sanitize(stripped[2:]), code_style))
        # 加粗条目
        elif stripped.startswith("**") and "**" in stripped[2:]:
            elements.append(Paragraph(_sanitize(stripped), body_style))
        # 列表项
        elif stripped.startswith("- ") or stripped.startswith("* "):
            elements.append(Paragraph("• " + _sanitize(stripped[2:]), body_style))
        # 其他
        else:
            elements.append(Paragraph(_sanitize(stripped), body_style))

    # 页脚
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=0.3, color=HexColor("#eeeeee")))
    elements.append(Paragraph(
        f"Generated by ESG Intelligence Agent | {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
        footer_style,
    ))

    return elements


def _sanitize(text: str) -> str:
    """转义 XML 特殊字符，保留中文。"""
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # 保留 emoji（reportlab 可能不支持，替换为文本标记）
    for emoji, alt in [
        ("🏛️", "[Report]"), ("🔮", "[Strategy]"), ("📅", "[Date]"),
        ("📊", "[Stats]"), ("📆", "[Period]"), ("📑", "[TOC]"),
        ("💡", "[Insight]"), ("📰", "[Source]"), ("🤖", "[Auto]"),
        ("⚠️", "[!]"), ("🔥", "[!!]"), ("⚡", "[!]"), ("✅", "[OK]"),
        ("🔴", "[CRIT]"), ("🟡", "[WARN]"), ("🟢", "[OK]"),
    ]:
        text = text.replace(emoji, alt)
    return text


def convert_markdown_to_pdf(md_path: str, pdf_path: str = None) -> str:
    """
    将 Markdown 报告转换为 PDF。

    Args:
        md_path: Markdown 文件路径
        pdf_path: 输出 PDF 路径，默认与 md 同目录同名 .pdf

    Returns:
        PDF 文件路径
    """
    md_path = Path(md_path)
    if not md_path.exists():
        raise FileNotFoundError(f"Markdown report not found: {md_path}")

    if pdf_path is None:
        pdf_path = str(md_path.with_suffix(".pdf"))

    md_text = md_path.read_text(encoding="utf-8")
    elements = _md_to_pdf_elements(md_text)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
        title=f"ESG Intelligence Report — {md_path.stem}",
    )
    doc.build(elements)

    logger.info(f"PDF written: {pdf_path} ({len(elements)} elements)")
    return pdf_path


def convert_markdown_to_pdf_bytes(md_text: str) -> BytesIO:
    """将 Markdown 文本转为 PDF bytes buffer（用于 API 流式返回）。"""
    elements = _md_to_pdf_elements(md_text)
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )
    doc.build(elements)
    buf.seek(0)
    return buf
