"""
esg_agent.reporters — Markdown 报告生成与推送
═══════════════════════════════════════════════════════════════════════════════
"""

from __future__ import annotations
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd

from .config import AgentConfig

logger = logging.getLogger("esg_agent")


class MarkdownReportWriter:
    """
    Markdown 报告生成器（v9 — 按风险标签聚合）
    """

    TAG_PRIORITY: dict[str, int] = {
        "【供应链断裂预警】": 1,
        "【地缘政治预警】": 2,
        "【市场准入预警】": 3,
        "【政策前沿】": 4,
        "【机构预警】": 5,
    }
    FALLBACK_TAG = "【日常运营风险】"

    def __init__(self, intelligence_data: list[dict], config: Optional[AgentConfig] = None, mode: str = "daily"):
        self.data = intelligence_data or []
        self.config = config
        self.mode = mode
        self.df = pd.DataFrame(self.data) if self.data else pd.DataFrame()

    @classmethod
    def _extract_tags(cls, row) -> list[str]:
        tags_val = row.get("tags", row.get("tag", ""))
        if isinstance(tags_val, list):
            return [str(t).strip() for t in tags_val if str(t).strip()]
        if isinstance(tags_val, str) and tags_val.strip():
            return [t.strip() for t in re.split(r"[,\s]+", tags_val) if t.strip()]
        return []

    @classmethod
    def _assign_primary_tag(cls, tags: list[str]) -> str:
        best_tag = cls.FALLBACK_TAG
        best_priority = 999
        for t in tags:
            p = cls.TAG_PRIORITY.get(t, 999)
            if p < best_priority:
                best_priority = p
                best_tag = t
        return best_tag

    @classmethod
    def _build_tag_groups(cls, df):
        primary_tags = df.apply(lambda row: cls._assign_primary_tag(cls._extract_tags(row)), axis=1)
        df = df.copy()
        df["_primary_tag"] = primary_tags
        groups = {tag: df[df["_primary_tag"] == tag] for tag in df["_primary_tag"].unique()}
        return dict(sorted(groups.items(), key=lambda item: cls.TAG_PRIORITY.get(item[0], 999)))

    def _get_report_title(self) -> str:
        if self.mode == "practice":
            return "🌱 同业良好实践周报 (Industry Best Practice Weekly)"
        elif self.mode == "weekly":
            return "🏛️ ESG Global Strategy Report"
        else:
            return "📊 ESG Daily Risk Radar"

    def generate(self, path: str = "esg_global_report.md") -> None:
        if self.df.empty or "company" not in self.df.columns:
            now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            if self.mode == "practice":
                empty_msg = "No best practice events detected this week."
            else:
                empty_msg = "No risk events detected today."
            Path(path).write_text(
                f"# {self._get_report_title()}\n\n> 📅 Generated: {now}\n\n{empty_msg}\n",
                encoding="utf-8",
            )
            logger.info(f"Empty report written to {path}")
            return

        lines = self._build_report()
        Path(path).write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Report saved: {path} ({len(self.df)} items)")

    def _build_report(self) -> list[str]:
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        total = len(self.df)
        firms = self.df["company"].nunique() if "company" in self.df.columns else 0
        tag_groups = self._build_tag_groups(self.df)
        tag_count = len(tag_groups)

        lines = [
            f"# {self._get_report_title()}",
            "",
            f"> 📅 Generated: {now}",
            f"> 📊 Total: {total} | Firms: {firms} | Tags: {tag_count}",
            "",
            "---",
            "",
            "## 📑 Contents",
            "",
        ]

        for tag, sub_df in tag_groups.items():
            lines.append(f"- **{tag}** ({len(sub_df)} items)")
            for company in sorted(sub_df["company"].unique()):
                co_count = len(sub_df[sub_df["company"] == company])
                lines.append(f"  - {company}: {co_count}")
            lines.append("")

        lines += ["---", ""]

        for tag, sub_df in tag_groups.items():
            sub_df = sub_df.copy()
            sub_df["_sort_dt"] = pd.to_datetime(sub_df.get("date", pd.Series(dtype=str)), errors="coerce")
            sub_df = sub_df.sort_values("_sort_dt", ascending=False, na_position="last")

            lines.append(f"### {tag}")
            lines.append(f"> {len(sub_df)} items")
            lines.append("")

            for _, row in sub_df.iterrows():
                lines.extend(self._render_item(row))

            lines += ["---", ""]

        lines += [
            "🤖 Generated by ESG Intelligence Agent.",
            "⚠️ For reference only, not investment or legal advice.",
        ]
        return lines

    @staticmethod
    def _render_item(row) -> list[str]:
        company = str(row.get("company", "")).strip()
        title = str(row.get("title", row.get("title_cn", ""))).strip()
        url = str(row.get("url", "")).strip()
        insight = str(row.get("insight", "")).strip()
        source = str(row.get("source", "Unknown"))[:50].strip()
        date_s = str(row.get("date", ""))[:10]

        if not url.lower().startswith("http") or len(url) < 12:
            url = "https://news.google.com"

        parts = []
        if company and title:
            parts.append(f"**{company}** | {title}\n\n")
        elif company:
            parts.append(f"**{company}**\n\n")
        elif title:
            parts.append(f"**{title}**\n\n")

        if insight:
            parts.append(f"💡 **Insight**: {insight}\n\n")

        meta_segments = []
        if date_s:
            meta_segments.append(f"📅 {date_s}")
        if source:
            meta_segments.append(f"📰 {source}")
        if url:
            meta_segments.append(f"🔗 [Read more]({url})")
        if meta_segments:
            parts.append(f"*{'   |   '.join(meta_segments)}*\n\n")

        parts.append("---\n\n")
        return [p for p in parts if p]
